#!/usr/bin/env bash
# This script displays information for a specified domain name

domain=$1
subdomain=$2

all_subdomains=( "www" "lb-01" "web-01" "web-02")

dns_lookup () {
	DOMAIN=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | grep -v 'ANSWER SECTION:')
	SUBDOMAIN=$(echo "$DOMAIN" | awk -F "." '{print $1}')
	RECORD_TYPE=$(echo "$DOMAIN" | awk '{print $4}')
	DESTINATION=$(echo "$DOMAIN" | awk '{print $5}')

	echo "The subdomain $SUBDOMAIN is a $RECORD_TYPE record and points to $DESTINATION"
}

if [[ -z $subdomain ]]; then
	for subdomain in "${all_subdomains[@]}"
	do
		dns_lookup "$domain" "$subdomain"
	done
elif [[ -n $subdomain ]]; then
	dns_lookup "$domain" "$subdomain"
fi
